# Generated by Django 5.2.14 on 2026-05-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(db_index=True, max_length=64)),
                ('posting_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('title', models.CharField(max_length=512)),
                ('link', models.URLField(max_length=1024, unique=True)),
                ('price', models.CharField(blank=True, max_length=64)),
                ('location', models.CharField(blank=True, max_length=256)),
                ('first_seen', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-first_seen'],
                'indexes': [models.Index(fields=['site', 'posting_id'], name='listings_li_site_a438d8_idx'), models.Index(fields=['-first_seen'], name='listings_li_first_s_f429fd_idx')],
            },
        ),
    ]
