# Generated by Django 5.2.14 on 2026-05-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='source',
            field=models.CharField(db_index=True, default='craigslist', max_length=32),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['source', 'site'], name='listings_li_source_404004_idx'),
        ),
    ]
